// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtMPbORk8KU5ajwqwQlmjZUz3dE02dBk4',
    appId: '1:294912661264:web:bc4924e72d3b754adf3795',
    messagingSenderId: '294912661264',
    projectId: 'test-app-df648',
    authDomain: 'test-app-df648.firebaseapp.com',
    storageBucket: 'test-app-df648.appspot.com',
    measurementId: 'G-LHVBMR9CYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9mHJ15bCmJf9ssLIJFipHOnlzgBvlEgs',
    appId: '1:294912661264:android:cbd2830e0bc116c9df3795',
    messagingSenderId: '294912661264',
    projectId: 'test-app-df648',
    storageBucket: 'test-app-df648.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZgAqd_2tjuvkKBSiGM1vgyUzomstEt1M',
    appId: '1:294912661264:ios:52fb2a15c9cbb0fcdf3795',
    messagingSenderId: '294912661264',
    projectId: 'test-app-df648',
    storageBucket: 'test-app-df648.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZgAqd_2tjuvkKBSiGM1vgyUzomstEt1M',
    appId: '1:294912661264:ios:3924cbb65132f594df3795',
    messagingSenderId: '294912661264',
    projectId: 'test-app-df648',
    storageBucket: 'test-app-df648.appspot.com',
    iosBundleId: 'com.example.testApp.RunnerTests',
  );
}
